# CentOS.yaml
#
# This source file is part of the SDGSwift open source project.
# https://sdggiesbrecht.github.io/SDGSwift
#
# Copyright Â©2021 Jeremy David Giesbrecht and the SDGSwift project contributors.
#
# Soli Deo gloria.
#
# Licensed under the Apache Licence, Version 2.0.
# See http://www.apache.org/licenses/LICENSE-2.0 for licence information.

name: CentOS

on: [push, pull_request]

jobs:
  CentOS:
    name: CentOS
    runs-on: ubuntu-20.04
    container: swift:5.4.0-centos8
    steps:
    - name: Check out
      uses: actions/checkout@v1
    - name: Cache Workspace
      uses: actions/cache@v1
      with:
        key: CentOSâ€${{ hashFiles('.github/workflows/**') }}
        path: .build/SDG/Workspace
    - name: Install SwiftPM dependencies
      shell: bash
      run: |
        set -x
        yum install --assumeyes \
          ncurses-devel \
          sqlite-devel
    - name: Install Workspace dependencies
      shell: bash
      run: |
        set -x
        yum install --assumeyes \
          curl
    - name: Install Workspace
      shell: bash
      run: |
        set -x
        if workspace version > /dev/null 2>&1 ; then
            echo "Using system install of Workspace..."
            workspace version â€¢language 'ğŸ‡¨ğŸ‡¦EN' â€¢useâ€version 0.37.0
        elif .build/SDG/Workspace/workspace version > /dev/null 2>&1 ; then
            echo "Using repository cache of Workspace..."
            .build/SDG/Workspace/workspace version â€¢language 'ğŸ‡¨ğŸ‡¦EN' â€¢useâ€version 0.37.0
        else
            echo "No cached build detected; fetching Workspace..."
            export OVERRIDE_INSTALLATION_DIRECTORY=.build/SDG
            curl -sL https://gist.github.com/SDGGiesbrecht/4d76ad2f2b9c7bf9072ca1da9815d7e2/raw/update.sh | bash -s Workspace "https://github.com/SDGGiesbrecht/Workspace" 0.37.0 "" workspace
            .build/SDG/Workspace/workspace version â€¢language 'ğŸ‡¨ğŸ‡¦EN' â€¢useâ€version 0.37.0
        fi
    - name: Refresh
      shell: bash
      run: |
        set -x
        if workspace version > /dev/null 2>&1 ; then
            echo "Using system install of Workspace..."
            workspace refresh â€¢language 'ğŸ‡¨ğŸ‡¦EN' â€¢useâ€version 0.37.0
        elif .build/SDG/Workspace/workspace version > /dev/null 2>&1 ; then
            echo "Using repository cache of Workspace..."
            .build/SDG/Workspace/workspace refresh â€¢language 'ğŸ‡¨ğŸ‡¦EN' â€¢useâ€version 0.37.0
        else
            echo "No cached build detected; fetching Workspace..."
            export OVERRIDE_INSTALLATION_DIRECTORY=.build/SDG
            curl -sL https://gist.github.com/SDGGiesbrecht/4d76ad2f2b9c7bf9072ca1da9815d7e2/raw/update.sh | bash -s Workspace "https://github.com/SDGGiesbrecht/Workspace" 0.37.0 "" workspace
            .build/SDG/Workspace/workspace refresh â€¢language 'ğŸ‡¨ğŸ‡¦EN' â€¢useâ€version 0.37.0
        fi
    - name: Validate
      shell: bash
      run: |
        set -x
        if workspace version > /dev/null 2>&1 ; then
            echo "Using system install of Workspace..."
            workspace validate â€¢job centos â€¢language 'ğŸ‡¨ğŸ‡¦EN' â€¢useâ€version 0.37.0
        elif .build/SDG/Workspace/workspace version > /dev/null 2>&1 ; then
            echo "Using repository cache of Workspace..."
            .build/SDG/Workspace/workspace validate â€¢job centos â€¢language 'ğŸ‡¨ğŸ‡¦EN' â€¢useâ€version 0.37.0
        else
            echo "No cached build detected; fetching Workspace..."
            export OVERRIDE_INSTALLATION_DIRECTORY=.build/SDG
            curl -sL https://gist.github.com/SDGGiesbrecht/4d76ad2f2b9c7bf9072ca1da9815d7e2/raw/update.sh | bash -s Workspace "https://github.com/SDGGiesbrecht/Workspace" 0.37.0 "" workspace
            .build/SDG/Workspace/workspace validate â€¢job centos â€¢language 'ğŸ‡¨ğŸ‡¦EN' â€¢useâ€version 0.37.0
        fi
    - name: Grant permission to cache
      shell: bash
      run: |
        set -x
        chmod -R a+rwx .
