# Swift 5.7 (watchOS).yaml
#
# This source file is part of the SDGSwift open source project.
# https://sdggiesbrecht.github.io/SDGSwift
#
# Copyright ©2021–2023 Jeremy David Giesbrecht and the SDGSwift project contributors.
#
# Soli Deo gloria.
#
# Licensed under the Apache Licence, Version 2.0.
# See http://www.apache.org/licenses/LICENSE-2.0 for licence information.

name: Swift 5.7 (watchOS)

on: [push, pull_request]

jobs:
  Swift_5_7_watchOS:
    name: Swift 5.7 (watchOS)
    runs-on: macos-12
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Set Xcode up
      shell: bash
      run: |
        set -x
        sudo xcode-select -switch /Applications/Xcode_14.0.app
        defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES
        xcodebuild -version
        swift --version
    - name: Validate
      shell: bash
      run: |
        set -x
        xcodebuild -resolvePackageDependencies
        xcodebuild build -destination 'generic/platform=watchOS' -scheme SDGSwift-Package
        xcodebuild test -destination 'platform=watchOS Simulator,name=Apple Watch Series 8 (41mm)' -scheme SDGSwift-Package
