# tvOS.yaml
#
# This source file is part of the SDGSwift open source project.
# https://sdggiesbrecht.github.io/SDGSwift
#
# Copyright Â©2021â€“2022 Jeremy David Giesbrecht and the SDGSwift project contributors.
#
# Soli Deo gloria.
#
# Licensed under the Apache Licence, Version 2.0.
# See http://www.apache.org/licenses/LICENSE-2.0 for licence information.

name: tvOS

on: [push, pull_request]

jobs:
  tvOS:
    name: tvOS
    runs-on: macos-12
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Cache Workspace
      uses: actions/cache@v2
      with:
        key: macOSâ€${{ hashFiles('.github/workflows/**') }}
        path: .build/SDG/Workspace
    - name: Set Xcode up
      shell: bash
      run: |
        set -x
        sudo xcode-select -switch /Applications/Xcode_14.0.app
        xcodebuild -version
        swift --version
    - name: Install Workspace
      shell: bash
      run: |
        set -x
        if workspace version > /dev/null 2>&1 ; then
            echo "Using system install of Workspace..."
            workspace version â€¢language 'ğŸ‡¨ğŸ‡¦EN' â€¢useâ€version 0.41.0
        elif .build/SDG/Workspace/workspace version > /dev/null 2>&1 ; then
            echo "Using repository cache of Workspace..."
            .build/SDG/Workspace/workspace version â€¢language 'ğŸ‡¨ğŸ‡¦EN' â€¢useâ€version 0.41.0
        else
            echo "No cached build detected; fetching Workspace..."
            export OVERRIDE_INSTALLATION_DIRECTORY=.build/SDG
            curl -sL https://gist.github.com/SDGGiesbrecht/4d76ad2f2b9c7bf9072ca1da9815d7e2/raw/update.sh | bash -s Workspace "https://github.com/SDGGiesbrecht/Workspace" 0.41.0 "" workspace
            .build/SDG/Workspace/workspace version â€¢language 'ğŸ‡¨ğŸ‡¦EN' â€¢useâ€version 0.41.0
        fi
    - name: Refresh
      shell: bash
      run: |
        set -x
        if workspace version > /dev/null 2>&1 ; then
            echo "Using system install of Workspace..."
            workspace refresh â€¢language 'ğŸ‡¨ğŸ‡¦EN' â€¢useâ€version 0.41.0
        elif .build/SDG/Workspace/workspace version > /dev/null 2>&1 ; then
            echo "Using repository cache of Workspace..."
            .build/SDG/Workspace/workspace refresh â€¢language 'ğŸ‡¨ğŸ‡¦EN' â€¢useâ€version 0.41.0
        else
            echo "No cached build detected; fetching Workspace..."
            export OVERRIDE_INSTALLATION_DIRECTORY=.build/SDG
            curl -sL https://gist.github.com/SDGGiesbrecht/4d76ad2f2b9c7bf9072ca1da9815d7e2/raw/update.sh | bash -s Workspace "https://github.com/SDGGiesbrecht/Workspace" 0.41.0 "" workspace
            .build/SDG/Workspace/workspace refresh â€¢language 'ğŸ‡¨ğŸ‡¦EN' â€¢useâ€version 0.41.0
        fi
    - name: Validate
      shell: bash
      run: |
        set -x
        if workspace version > /dev/null 2>&1 ; then
            echo "Using system install of Workspace..."
            workspace validate â€¢job tvos â€¢language 'ğŸ‡¨ğŸ‡¦EN' â€¢useâ€version 0.41.0
        elif .build/SDG/Workspace/workspace version > /dev/null 2>&1 ; then
            echo "Using repository cache of Workspace..."
            .build/SDG/Workspace/workspace validate â€¢job tvos â€¢language 'ğŸ‡¨ğŸ‡¦EN' â€¢useâ€version 0.41.0
        else
            echo "No cached build detected; fetching Workspace..."
            export OVERRIDE_INSTALLATION_DIRECTORY=.build/SDG
            curl -sL https://gist.github.com/SDGGiesbrecht/4d76ad2f2b9c7bf9072ca1da9815d7e2/raw/update.sh | bash -s Workspace "https://github.com/SDGGiesbrecht/Workspace" 0.41.0 "" workspace
            .build/SDG/Workspace/workspace validate â€¢job tvos â€¢language 'ğŸ‡¨ğŸ‡¦EN' â€¢useâ€version 0.41.0
        fi
